{"errorMessage": "Unknown service: 's3'. Valid service names are: ", "errorType": "UnknownServiceError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n", "  File \"/var/task/lambda_function.py\", line 10, in <module>\n    s3 = boto3.client('s3', endpoint_url=os.getenv(\"LOCALSTACK_ENDPOINT\"))\n", "  File \"/var/task/boto3/__init__.py\", line 92, in client\n    return _get_default_session().client(*args, **kwargs)\n", "  File \"/var/task/boto3/session.py\", line 322, in client\n    return self._session.create_client(\n", "  File \"/var/task/botocore/session.py\", line 1015, in create_client\n    client = client_creator.create_client(\n", "  File \"/var/task/botocore/client.py\", line 132, in create_client\n    service_model = self._load_service_model(service_name, api_version)\n", "  File \"/var/task/botocore/client.py\", line 239, in _load_service_model\n    json_model = self._loader.load_service_model(\n", "  File \"/var/task/botocore/loaders.py\", line 143, in _wrapper\n    data = func(self, *args, **kwargs)\n", "  File \"/var/task/botocore/loaders.py\", line 409, in load_service_model\n    raise UnknownServiceError(\n"]}